# Generated by Django 4.1.3 on 2022-11-06 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
